version: "3.9"

services:
  db:
    image: postgres:15
    container_name: resume_db
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: resume_backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env

  ai-service:
    build: ./ai-service
    container_name: resume_ai
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./ai-service:/app
    ports:
      - "8001:8001"
    env_file:
      - ./ai-service/.env

volumes:
  postgres_data:
